// Cartografia Viva — página de serviço: uma ficha de campo que conduz da necessidade à conversa.
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, MapPin, Plus, X } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { Header, Footer, WhatsAppFloat } from "@/components/SiteChrome";
import { company, whatsappUrl } from "@/data/company";
import { services } from "@/data/services";

function Gallery({ images, title }: { images: string[]; title: string }) {
  const [active, setActive] = useState<number | null>(null);
  const [index, setIndex] = useState(0);
  const available = images.map((src, i) => ({ src, fallback: i === 0 ? "/manus-storage/vertente-hero_69fb3e42.jpg" : i === 1 ? "/manus-storage/vertente-reflorestar_389e947e.jpg" : "/manus-storage/vertente-field_1381125a.jpg" }));
  return <><div className="grid gap-4 sm:grid-cols-3">{available.map((item, i) => <button key={item.src} onClick={() => { setIndex(i); setActive(i); }} className="group relative aspect-[4/3] overflow-hidden rounded-2xl bg-sand text-left"><img src={item.src} alt={`${title} — imagem ${i + 1}`} className="h-full w-full object-cover opacity-70 transition duration-500 group-hover:scale-105 group-hover:opacity-100" onError={(e) => { e.currentTarget.src = item.fallback; }} /><span className="absolute bottom-3 right-3 grid size-9 place-items-center rounded-full bg-paper/90 text-forest"><Plus size={16} /></span><span className="absolute left-3 top-3 tag bg-forest/80 text-white">{String(i + 1).padStart(2, "0")}</span></button>)}</div>{active !== null && <div className="fixed inset-0 z-[60] grid place-items-center bg-forest/95 p-5" role="dialog" aria-modal="true" aria-label="Galeria ampliada"><button className="absolute right-5 top-5 grid size-11 place-items-center rounded-full border border-white/20 text-white" onClick={() => setActive(null)} aria-label="Fechar galeria"><X /></button><button className="absolute left-5 grid size-11 place-items-center rounded-full border border-white/20 text-white" onClick={() => setIndex((index - 1 + available.length) % available.length)} aria-label="Imagem anterior"><ChevronLeft /></button><img src={available[index].src} alt={`${title} — imagem ampliada`} className="max-h-[80vh] max-w-[90vw] rounded-2xl object-contain" onError={(e) => { e.currentTarget.src = available[index].fallback; }} /><button className="absolute right-5 grid size-11 place-items-center rounded-full border border-white/20 text-white" onClick={() => setIndex((index + 1) % available.length)} aria-label="Próxima imagem"><ChevronRight /></button><p className="absolute bottom-6 text-xs uppercase tracking-[0.2em] text-white/50">{index + 1} / {available.length}</p></div>}</>;
}

export default function ServicePage({ forcedSlug }: { forcedSlug?: string }) {
  const [, params] = useRoute("/servicos/:slug");
  const [, navigate] = useLocation();
  const service = services.find(item => item.slug === (forcedSlug ?? params?.slug));
  useEffect(() => { if (service) document.title = `${service.title} — Vertente Vegetal`; }, [service]);
  if (!service) return <div className="grid min-h-screen place-items-center bg-paper p-6 text-center"><div><p className="eyebrow text-ocre">Página não encontrada</p><h1 className="mt-4 font-display text-5xl text-forest">Esse caminho ainda não foi mapeado.</h1><Link href="/" className="mt-7 inline-flex rounded-full bg-forest px-5 py-3 text-sm font-bold text-white">Voltar ao início</Link></div></div>;
  const isReflorestar = service.slug === "programa-reflorestar";
  return <div className="min-h-screen bg-paper text-ink"><Header /><main><section className="relative flex min-h-[650px] items-end overflow-hidden bg-forest pb-16 pt-36 text-white md:min-h-[700px] md:pb-24"><img src={service.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-65" /><div className="absolute inset-0 bg-gradient-to-t from-forest via-forest/35 to-forest/15" /><div className="container relative z-10"><Link href="/#servicos" className="mb-20 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-white/60 hover:text-ocre"><ArrowLeft size={15} /> Todos os serviços</Link><p className="eyebrow text-ocre">{service.eyebrow}</p><h1 className="mt-4 max-w-4xl break-words font-display text-[clamp(3.5rem,8vw,7rem)] leading-[0.86] tracking-tight">{service.title}</h1><p className="mt-7 max-w-xl text-lg leading-7 text-white/70">{service.summary}</p><a href={whatsappUrl} className="mt-8 inline-flex items-center gap-3 rounded-full bg-ocre px-6 py-4 text-sm font-bold text-white hover:-translate-y-1 hover:bg-white hover:text-forest">Conversar sobre este serviço <ArrowRight size={17} /></a></div></section>
    <section className="py-24 md:py-32"><div className="container grid gap-14 lg:grid-cols-[0.72fr_1.28fr]"><div><p className="eyebrow text-forest/55">Por que importa</p><h2 className="mt-4 font-display text-4xl leading-none text-forest md:text-5xl">A clareza muda o próximo passo.</h2></div><div><p className="text-xl leading-8 text-ink/75">{service.importance}</p><div className="mt-12 grid gap-10 border-t border-ink/10 pt-10 md:grid-cols-2"><div><p className="eyebrow text-ocre">O que fazemos</p><p className="mt-4 text-sm leading-7 text-ink/65">{service.whatWeDo}</p></div><div><p className="eyebrow text-ocre">Quando pode fazer sentido</p><ul className="mt-4 space-y-3 text-sm leading-6 text-ink/65">{service.when.map(item => <li key={item} className="flex gap-3"><Check size={16} className="mt-1 shrink-0 text-ocre" />{item}</li>)}</ul></div></div></div></div></section>
    {isReflorestar && <section className="relative bg-sand py-24 md:py-28"><div className="pointer-events-none absolute right-8 top-10 hidden text-[10px] font-bold uppercase tracking-[0.2em] text-ink/30 lg:block">legenda · conservação + oportunidade</div><div className="container grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="eyebrow text-ocre">Programa Reflorestar</p><h2 className="mt-4 font-display text-5xl leading-[0.92] text-forest">Recuperar também pode ser planejar.</h2></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-paper p-6"><h3 className="font-display text-2xl text-forest">Para quem é</h3><p className="mt-3 text-sm leading-6 text-ink/60">Para proprietários que querem entender oportunidades de recuperação, conservação e uso responsável de áreas rurais.</p></div><div className="rounded-2xl bg-paper p-6"><h3 className="font-display text-2xl text-forest">Como começa</h3><p className="mt-3 text-sm leading-6 text-ink/60">Com uma avaliação do cenário da propriedade e uma conversa sobre possibilidades de enquadramento.</p></div><div className="rounded-2xl bg-forest p-6 text-white sm:col-span-2"><h3 className="font-display text-2xl">Sem adivinhar o território</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Modalidades, requisitos e incentivos dependem da análise e das regras aplicáveis. A Vertente ajuda a organizar essa leitura com você.</p></div></div></div></section>}
    <section className="relative py-24 md:py-32"><div className="pointer-events-none absolute right-8 top-16 hidden text-[10px] font-bold uppercase tracking-[0.2em] text-ink/30 lg:block">ficha de campo · rota 01</div><div className="container grid gap-14 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="eyebrow text-forest/55">Como podemos ajudar</p><h2 className="mt-4 font-display text-4xl leading-none text-forest md:text-5xl">Um caminho possível, etapa por etapa.</h2></div><div className="grid gap-0">{service.process.map((step, i) => <div key={step} className="flex gap-5 border-b border-ink/10 py-5"><span className="font-mono text-sm text-ocre">0{i + 1}</span><p className="text-base text-ink/70">{step}</p></div>)}<a href={whatsappUrl} className="mt-8 inline-flex w-fit items-center gap-3 rounded-full bg-forest px-6 py-4 text-sm font-bold text-white hover:-translate-y-1 hover:bg-ocre">Fale com a Vertente <ArrowRight size={17} /></a></div></div></section>
    <section className="bg-sand py-24 md:py-28"><div className="container"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-ocre">Portfólio visual</p><h2 className="mt-4 font-display text-4xl text-forest md:text-5xl">Imagens da prática.</h2></div><p className="max-w-xs text-sm leading-6 text-ink/55">Registros visuais, leituras do terreno e detalhes que ajudam a contar o cenário.</p></div><div className="mt-10"><Gallery images={service.gallery} title={service.title} /></div></div></section>
    <section className="bg-ocre py-20 text-white"><div className="container flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="eyebrow text-white/65">Próximo passo</p><h2 className="mt-3 max-w-2xl font-display text-4xl leading-none md:text-5xl">Quer entender o que esse serviço pode significar para a sua propriedade?</h2></div><a href={whatsappUrl} className="inline-flex shrink-0 items-center justify-center gap-3 rounded-full bg-forest px-6 py-4 text-sm font-bold hover:bg-white hover:text-forest">{isReflorestar ? "Quero saber se posso me enquadrar" : "Conversar sobre minha área"} <ArrowRight size={17} /></a></div></section></main><Footer /><WhatsAppFloat /></div>;
}
